language: node_js

node_js:
  - "6"

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -t zixia/wechaty .; fi

script:
  - echo $TRAVIS_OS_NAME
  - echo $GITTER_IM_URL
  - npm test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run zixia/wechaty test; fi

notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
      - https://registry.hub.docker.com/u/zixia/wechaty/trigger/01585c2b-175b-4d27-b09d-e380a052c17c/
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
