language: node_js

node_js:
  - "6"

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

services:
  - docker

install:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew tap caskroom/cask; fi 
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install brew-cask; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew cask install google-chrome; fi
  
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then export DISPLAY=':99.0'; fi
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then (Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &); fi

script:
  - echo $TRAVIS_OS_NAME
  - npm test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -t zixia/wechaty .; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run zixia/wechaty test; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -X POST $DOCKER_REBUILD_URL; fi
