language: node_js

node_js:
  - "6"

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -t zixia/wechaty .

script:
  - npm test
  - docker run zixia/wechaty test

notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
