language: node_js
node_js:
  - "6.1"
  - "6"
before_install:
  - env
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
cache:
  directories:
    - node_modules
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

