version: 2

jobs:
  test:
    parallelism: 1
    docker:
      - image: scholzj/circleci-centos-golang

    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
        name: Unit Testing
        command: |
          curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -
          sudo yum -y install nodejs
          sudo yum -y install gcc-c++ make
          npm install
          npm test

workflows:
  version: 2
  test-flow:
    jobs:
      - test
