version: 2
jobs:
  test:
    docker:
      - image: scholzj/circleci-centos-golang
    steps:
      - checkout
      - run: npm install && npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
