version: 2
jobs:
  test:
    docker:
      - image: scholzj/circleci-centos-golang
    steps:
      - checkout
      - run:
        curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -
        sudo yum -y install nodejs
        sudo yum install gcc-c++ make
        npm install
        npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
