name: Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs/heads/v[0-9]+\.[0-9]+.*$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Build
        if: steps.check-branch.outputs.match == 'true'
        run: |
          echo "Tag is a match"
      - name: Skip
        if: steps.check-branch.outputs.match != 'true'
        run: echo 'Not Version Branch'
